package: pydna
platform:
  - linux-64
  #- linux-32
  #- osx-64
  #- win-32
  #- win-64

build_targets: conda
script:
  - conda update -n root conda-build
  - conda config --add channels omnia
  - conda config --add channels synthicity
  - conda build .









