package: pydna
platform:
  - linux-64
engine:
  - python=2.7

test:
  - bash -c 'echo Hello Posix World'
  #- conda install nose

env:
  - FOO=BAR
  #- BINSTAR=GREAT JENKINS=OK

before_script:
  - conda update -n root conda
  - conda install binstar binstar-build
  - conda update -n root conda-build
  - conda config --add channels omnia
  - conda config --add channels synthicity

script:
  - conda build .

build_targets: conda 

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all 
  - binstar -q -t $TOKEN upload --force --user BjornFJohansson --package pydna  --channel dev /opt/miniconda/conda-bld/linux-64/*.tar.bz2 --build-id 2.0
  - binstar -q -t $TOKEN upload --force --user BjornFJohansson --package pydna  --channel dev /opt/miniconda/conda-bld/linux-32/*.tar.bz2 --build-id 2.0
  - binstar -q -t $TOKEN upload --force --user BjornFJohansson --package pydna  --channel dev /opt/miniconda/conda-bld/osx-64/*.tar.bz2 --build-id 2.0
  - binstar -q -t $TOKEN upload --force --user BjornFJohansson --package pydna  --channel dev /opt/miniconda/conda-bld/win-64/*.tar.bz2 --build-id 2.0
  - binstar -q -t $TOKEN upload --force --user BjornFJohansson --package pydna  --channel dev /opt/miniconda/conda-bld/win-32/*.tar.bz2 --build-id 2.0
after_failure:
  - echo Oops?





