package: pydna
platform:
  - linux-64
engine:
  - python=2.7

test:
  - bash -c 'echo Hello Posix World'
  #- conda install nose

env:
  - FOO=BAR
  #- BINSTAR=GREAT JENKINS=OK

before_script:
  - conda update -n root conda
  - conda install binstar binstar-build
  - conda update -n root conda-build
  - conda config --add channels omnia
  - conda config --add channels synthicity

script:
  - conda build .

build_targets: conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all

after_script:  
  - echo After script!
  - conda 

after_success:
  - echo Yay!

after_failure:
  - echo Oops?





