package: pydna
platform:
  - linux-64
engine:
  - python=2.7

build_targets: conda

test:
  - bash -c 'echo Hello Posix World'
  #- conda install nose

env:
  - FOO=BAR
  #- BINSTAR=GREAT JENKINS=OK

before_script:
  - conda update -n root conda
  - conda install binstar binstar-build
  - conda update -n root conda-build
  - conda config --add channels omnia
  - conda config --add channels synthicity
  - binstar --version
  - conda --version
  #- conda config --add channels binstar
  #- conda install binstar-build
  #- binstar config --set url http://api.alpha.binstar.org
  #- binstar whoami
  #- echo $TOKEN
  #- conda install pip
  #- pip install binstar binstar-build

script:
  - conda build .

after_script:  
  - echo After script!

after_success:
  - echo Yay!

after_failure:
  - echo Oops?





