package: pydna
user: BjornFJohansson

platform:
  - linux-64
engine:
  - python=2.7

before_script:
  #- git describe --tags --always
  #- git describe --tags
   #- conda update -n root conda
   #- conda install anaconda-client anaconda-build
   #- conda update -n root conda-build
  #- conda config --add channels ulmo
  #- conda config --add channels synthicity
  #- conda config --add channels BjornFJohansson
  - cat $CONDARC
  #- cat ~/.condarc
test:
  - bash -c 'echo Hello Posix World'
  - cd pydna
  - python run_test.py
  #- conda install nose

script:
  #- python setup.py version
  #- conda build .
  #- conda build -c andreas-h 
  - conda build -c BjornFJohansson .

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all --output-dir /opt/miniconda/conda-bld/
after_failure:
  - echo Oops?

build_targets:
    files: /opt/miniconda/conda-bld/*/*.tar.bz2
    channels: 'main'

notifications:
  email:
    recipients: ['bjornjobb@gmail.com']

#https://anaconda.org/BjornFJohansson/pydna/0.9.9/download/osx-64/pydna-0.9.9-py27_1.tar.bz2
#https://api.anaconda.org/release/BjornFJohansson/pydna/
