package: pydna

before_script:
  - git describe --tags
  - conda update -n root conda
  - conda install binstar binstar-build
  - conda update -n root conda-build
  - conda config --add channels ulmo
  - conda config --add channels synthicity

test:
  - bash -c 'echo Hello Posix World'
  #- conda install nose

script:
  - python setup.py version
  - conda build .

build_targets:
    files: /opt/miniconda/conda-bld/*/*.tar.bz2
    channels: 'main'

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all --output-dir /opt/miniconda/conda-bld/
after_failure:
  - echo Oops?





