package: pydna
platform:
  - linux-64
engine:
  - python=2.7

test:
  - bash -c 'echo Hello Posix World'
  #- conda install nose

before_script:
  - conda update -n root conda
  - conda install binstar binstar-build
  - conda update -n root conda-build
  - conda config --add channels omnia
  - conda config --add channels synthicity

script:
  - conda build .

build_targets:
    files: /opt/miniconda/conda-bld/*/*.tar.bz2
    channels: main

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all --output-dir /opt/miniconda/conda-bld/
after_failure:
  - echo Oops?





