language: objective-c
sudo: false
cache:
 - wget
 - pip
 - conda

before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update -y -q conda
- conda config --add channels conda-forge 
- conda config --add channels BjornFJohansson
- conda install -y -q conda-build
- conda install -y -q nose
- conda install -y -q ipython
- conda install -y -q jupyter
- conda install -y -q biopython
- conda install -y -q networkx
- conda install -y -q appdirs
- conda install -y -q prettytable
- conda install -y -q numpy
- conda install -y -q scipy
- conda install -y -q matplotlib
- conda install -y -q mpldatacursor
- conda install -y -q pint
- conda install -y -q ordered-set
#- conda install -y -q python-coveralls
install:
  #- pip install coveralls
  - conda develop .
  
#script:
#  - coverage run run_test.py

#after_success:
#  coveralls
