language: python
python:
  - "2.7"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
script: 
# - python run_tests.py
# - py.test pydna/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  - nosetests -w tests -v --with-coverage
  - nosetests -w pydna --with-coverage --with-doctest -v

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: bjorn
  password: secure: "PLNlCt++35qR1sLrlzT0ys/WUxUNPh8isnxpEvAbfDWvgLBZc2vMWMr4HHNqv6UK4jvu9cwfAHJIcH+1tUxdMfs9Q8InqtyrFJgTU+VREhO/nyJgLah1CdmJ9ZixynOTUu8tuZNjX17ycPDM2fRxv0svY/mT2Z0U6nqX4eFFjic=
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/pydna
    condition: "$TRAVIS_TAG == ^[0-9][.][0-9][.][0-9]"

after_success:
  - coveralls

# try again
#   condition: "$TOXENV == py27 && $TRAVIS_TAG =~ ^[0-9][.][0-9]*[02468][.]"
