language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install -e .
before_script:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
   #- mkdir test_install_directory
   #- python setup.py sdist
   #- cp ./dist/pydna* ./test_install_directory/
   #- cd test_install_directory
   #- tar -zxvf pydna*
   #- cd pydna*
   #- python setup.py install
   #- python -c "import pydna;print '#'*80;print pydna.__version__;print '#'*80"
   #- cd ../..
   #- nosetests -v -w tests --with-coverage --with-doctest
   #- nosetests -v -w pydna --with-coverage --with-doctest
    - cd tests
    - nosetests --all-modules --verbosity=3 --nocapture --with-doctest --doctest-options=+ELLIPSIS
    - cd ../pydna
    - nosetests --all-modules --verbosity=3 --nocapture --with-doctest --doctest-options=+ELLIPSIS
    - cd ..

after_success:
  - coveralls
before_deploy: "echo 'ready?'"

deploy:
  provider: pypi
  distributions: "sdist --formats=gztar,zip bdist_wheel"
  user: bjorn
  password:
    secure: "PLNlCt++35qR1sLrlzT0ys/WUxUNPh8isnxpEvAbfDWvgLBZc2vMWMr4HHNqv6UK4jvu9cwfAHJIcH+1tUxdMfs9Q8InqtyrFJgTU+VREhO/nyJgLah1CdmJ9ZixynOTUu8tuZNjX17ycPDM2fRxv0svY/mT2Z0U6nqX4eFFjic="
#   server: https://testpypi.python.org/pypi
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/pydna

after_deploy:
  - pip uninstall -r requirements.txt -y 
  - pip uninstall -y pydna
  - sudo rm -r *
  - pip install pydna 
  - python -c "import pydna;print '#'*80;print pydna.__version__;print '#'*80"

  
#condition: "$TRAVIS_TAG == ^[0-9][.][0-9][.][0-9]"
