language: objective-c
os:
  - osx
before_install:
  - brew update
  - brew install python

install:
  #- brew install python --universal --framework
  #- brew install wget
  #- which python
  #- export VERSIONER_PYTHON_PREFER_32_BIT=yes
  #- defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
  #- which python
  #- python --version
  - pip install --upgrade pip
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install mpldatacursor
  - pip install -e .
 
before_script:

  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  - pip install ipython
  - pip install jsonschema
  
script:
  - python run_test_.py
