environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"
init:
- "set path C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%"
- conda update -y -q conda
- conda install -y conda-build anaconda-client
- conda-build -V
install:
- conda config --add channels conda-forge 
- conda config --add channels BjornFJohansson
- conda env create -f build_environment.yml
- activate pydnacondabuild
build_script:
- conda build .
