package:
    name: pydna
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  
source:
  git_url: .

requirements:
    build:
        - python
        - appdirs
        - biopython
        - prettytable
        - networkx
        - ordered-set
        - pyparsing

        - pytest
        - pytest-runner
        - setuptools
    run:
        - python
        - appdirs
        - biopython
        - prettytable
        - networkx
        - ordered-set
        - pyparsing
        - requests

        - ipython
        - jupyter
        - numpy
        - scipy
        - matplotlib
        - mpldatacursor
        - pint
test:
  requires:
    - pytest
  imports:
    - pydna
  source_files:
    - tests
    - pydna
about:
  home: https://github.com/BjornFJohansson/pydna
  license: BSD
  summary: Representing double stranded DNA and simulating cloning, homologous recombination, Gibson assembly, Gel electrophoresis etc.
  license_file: LICENSE.txt
extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
