package:
    name: pydna
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    path:

requirements:
    build:
        - python
        - ipython
        - biopython
        - networkx
        - appdirs
        - prettytable
        - numpy
        - scipy
        - matplotlib
        - mpldatacursor
        - pint
    run:
        - python
        - ipython
        - biopython
        - networkx
        - appdirs
        - prettytable
        - numpy
        - scipy
        - matplotlib
        - mpldatacursor
        - pint
about:
  home: https://github.com/BjornFJohansson/pydna
  license: BSD
  summary: Classes and code for representing double stranded DNA and functions for simulating homologous recombination and Gibson assembly.

