package:
    name: pydna
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  
source:
  git_url: .

requirements:
    build:
        - python
        - appdirs
        - biopython
        - prettytable
        - networkx
        - ordered-set
        - pyparsing

        - pytest
        - pytest-runner
        - setuptools
    run:
        - python
        - appdirs
        - biopython
        - prettytable
        - networkx
        - ordered-set
        - pyparsing

        - ipython
        - jupyter
        - numpy
        - scipy
        - matplotlib
        - mpldatacursor
        - pint

test:
  requires:
    - pytest
  imports:
    - pydna
  source_files:
    - tests
    - pydna

about:
  home: https://github.com/BjornFJohansson/pydna
  license: BSD
  summary: Classes for representing double stranded DNA and functions for simulating cloning, homologous recombination and Gibson assembly.

extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
