name: testenv35
channels:
- defaults
- conda-forge
- BjornFJohansson
dependencies:
- python=3.5
- appdirs
- biopython
- prettytable
- networkx
- ordered-set
- pyparsing



- ipython
- jupyter
- numpy
- scipy
- matplotlib
- mpldatacursor
- pint

- pytest
- coverage>=4.4
- python-coveralls
- pytest-cov
- pytest-runner
- nbval

- setuptools
- requests-mock


