package:
    name: pydna
    version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:]+environ.get('GIT_DESCRIBE_NUMBER', '') }}

source:
    path: ..

requirements:
    build:
        - python
        - ipython
        - biopython
        - networkx
        - appdirs
        - prettytable
    run:
        - python
        - ipython
        - biopython
        - networkx
        - appdirs
        - prettytable

about:
  home: https://github.com/BjornFJohansson/pydna
  license: BSD
  summary: Classes and code for representing double stranded DNA and functions for simulating homologous recombination and Gibson assembly.
